remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [OP-AND]
description: [Curated Database for Predicting Osteogenic Peptides]
